name: 'PPSL-Sync'
description: 'Synchronize PPSL-Data to MediaWiki.'
inputs:
  mediawiki-api-endpoint:
    description: 'The url for the MediaWiki API endpoint.'
    required: true
    default: 'https://endpoint.wiki/api.php'
  repo-local-path:
    description: 'The repository local path.'
    required: true
    default: './ppsl-data'
outputs:
  time:
    description: 'Finished time.'
runs:
  using: 'node12'
  main: 'src/index.mjs'
